#ifndef COMMON_COMMONDEFINES_H_
#define COMMON_COMMONDEFINES_H_
enum TrollDefines {
  TROLL_RUN_START_FRAME_IDX = 30,
  TROLL_RUN_END_FRAME_IDX = 39,
};
typedef enum {
  TEXTURE_WHEEL,
  TEXTURE_RUNNING_GIRL,
  TEXTURE_WHEEL_START_BUTTON,
  TEXTURE_WHEEL_STOP_BUTTON,
  TEXTURE_BACKGROUND,
  TEXTURE_GAME_OVER,
  TEXTURE_WIN_GAME,
  TEXTURE_TROLL_1_ID,
} Images;

typedef enum {
    RUNNING_GIRL_ID,
    WHEEL_ID,
    START_BUTTON_ID,
    STOP_BUTTON_ID ,
    BACKGROUND_ID,
    GAME_OVER_ID,

    TROLL_1_ID,
    TROLL_1_RUN_ID,
    TROLL_1_ATACK_ID,
    TROLL_1_DIE_ID,
    TROLL_1_HURT_ID,
    TROLL_1_IDLE_ID,

    TROLL_1_BUTTON_ID,
    TROLL_1_BUTTON_ENEMY_ID,

    PLAYER_TOWER_ID,
    ENEMY_TOWER_ID,
}TextureIdf;

typedef enum {
    ANGELINE_VINATGE_ID,
}FontIdf;

#endif