#ifndef COMMON_COMMONDEFINES_H_
#define COMMON_COMMONDEFINES_H_

// typedef enum {
//   TEXTURE_WHEEL,
//   TEXTURE_RUNNING_GIRL,
//   TEXTURE_WHEEL_START_BUTTON,
//   TEXTURE_WHEEL_STOP_BUTTON,
//   TEXTURE_BACKGROUND,
//   TEXTURE_GAME_OVER,
//   TEXTURE_WIN_GAME,
//   TEXTURE_TROLL_1_ID,
// } Images;
typedef enum{
    EASY,
    HARD,
    IMPOSSIBLE,
}GameMode;
typedef enum {
    RUNNING_GIRL_ID,
    WHEEL_ID,
    START_BUTTON_ID,
    STOP_BUTTON_ID ,
    BACKGROUND_ID,
    START_GAME_ID,

    GAME_OVER_ID,
    WIN_GAME_ID,

    COIN_ID,
    
    BUTTON_TABLE_ID,

    TROLL_1_ID,
    TROLL_1_RUN_ID,
    TROLL_1_ATACK_ID,
    TROLL_1_DIE_ID,
    TROLL_1_HURT_ID,
    TROLL_1_IDLE_ID,

    TROLL_2_ID,
    TROLL_2_RUN_ID,
    TROLL_2_ATACK_ID,
    TROLL_2_DIE_ID,
    TROLL_2_HURT_ID,
    TROLL_2_IDLE_ID,

    TROLL_3_ID,
    TROLL_3_RUN_ID,
    TROLL_3_ATACK_ID,
    TROLL_3_DIE_ID,
    TROLL_3_HURT_ID,
    TROLL_3_IDLE_ID,

    TERRORIST_1_ID,
    TERRORIST_1_RUN_ID,
    TERRORIST_1_ATACK_ID,
    TERRORIST_1_LONG_ATACK_ID,
    TERRORIST_1_HURT_ID,
    TERRORIST_1_IDLE_ID,
    TERRORIST_1_DIE_ID,

    TERRORIST_2_ID,
    TERRORIST_2_RUN_ID,
    TERRORIST_2_ATACK_ID,
    TERRORIST_2_LONG_ATACK_ID,
    TERRORIST_2_HURT_ID,
    TERRORIST_2_IDLE_ID,
    TERRORIST_2_DIE_ID,

    TERRORIST_3_ID,
    TERRORIST_3_RUN_ID,
    TERRORIST_3_ATACK_ID,
    TERRORIST_3_LONG_ATACK_ID,
    TERRORIST_3_HURT_ID,
    TERRORIST_3_IDLE_ID,
    TERRORIST_3_DIE_ID,

    ROBOT_1_ID,
    ROBOT_1_RUN_ID,
    ROBOT_1_ATACK_ID,
    ROBOT_1_LONG_ATACK_ID,
    ROBOT_1_HURT_ID,
    ROBOT_1_IDLE_ID,
    ROBOT_1_DIE_ID,

    ROBOT_2_ID,
    ROBOT_2_RUN_ID,
    ROBOT_2_ATACK_ID,
    ROBOT_2_LONG_ATACK_ID,
    ROBOT_2_HURT_ID,
    ROBOT_2_IDLE_ID,
    ROBOT_2_DIE_ID,

    ROBOT_3_ID,
    ROBOT_3_RUN_ID,
    ROBOT_3_ATACK_ID,
    ROBOT_3_LONG_ATACK_ID,
    ROBOT_3_HURT_ID,
    ROBOT_3_IDLE_ID,
    ROBOT_3_DIE_ID,

    TROLL_1_BUTTON_ID,
    TROLL_2_BUTTON_ID,
    TROLL_3_BUTTON_ID,

    TROLL_1_BUTTON_ENEMY_ID,
    TROLL_2_BUTTON_ENEMY_ID,
    TROLL_3_BUTTON_ENEMY_ID,

    TERRORIST_1_BUTTON_ID,
    TERRORIST_2_BUTTON_ID,
    TERRORIST_3_BUTTON_ID,

    TERRORIST_1_BUTTON_ENEMY_ID,
    TERRORIST_2_BUTTON_ENEMY_ID,
    TERRORIST_3_BUTTON_ENEMY_ID,

    ROBOT_1_BUTTON_ID,
    ROBOT_2_BUTTON_ID,
    ROBOT_3_BUTTON_ID,
    ROBOT_1_BUTTON_ENEMY_ID,
    ROBOT_2_BUTTON_ENEMY_ID,
    ROBOT_3_BUTTON_ENEMY_ID,

    STAR_BUTTON_ID,

    START_GAME_BUTTON_ID,

    PLAYER_TOWER_ID,
    ENEMY_TOWER_ID,
}TextureIdf;

typedef enum {
    ANGELINE_VINATGE_ID,
}FontIdf;

#endif