#ifndef TERRORIST_COMMONDEFINES_H_
#define TERRORIST_COMMONDEFINES_H_
typedef enum {
  TERRORIST_1_HEALTH = 75,
  TERRORIST_1_SHORT_ATACK_DEMAGE = 50,
  TERRORIST_1_LONG_ATACK_DEMAGE = 100,
  TERRORIST_1_SPRITE_FRAMES = 6,

} Terorist_1_defines;
#endif