#ifndef COMMON_TIMERS_H_
#define COMMON_TIMERS_H_

typedef enum {
  WHEEL_ANIM_TIMER_ID,
  HERO_CHANGE_SPRITE_TIMER_ID,
  HERo_MOVE_TIMER_ID,
  TROLL_1_CHANGE_SPRITE_TIMER_ID,
  TROLL_1_MOVE_TIMER_ID,

  TIMERS_COUNT
} TimerIds;

#endif 